# Generated by Django 3.1 on 2020-11-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0004_auto_20200818_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mytasks.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytasks.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytasks.user', verbose_name='Никнейм'),
        ),
    ]
