# Generated by Django 3.1 on 2021-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0006_auto_20201127_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
